### ISSUE TITLE
[RFC] Consider using Money library

### ISSUE THREAD

**Issue by umpirsky** [florianv/swap#15]
Hi.

First of all, thanks for this great library.

I just wanted to suggest something, what do you think about using https://github.com/mathiasverraes/money? 

It provides `CurrencyPair` for example.

**Comment by florianv** [comment]
Hi, 

thanks for your feedback.

We could rely on it but it should be extended, for example Swap provides the date at which the rate was calculated. This could be done but only in the next major version.

Maybe the easiest way is to create a wrapper around Swap that returns a `CurrencyPair` from the Money library instead of a `Rate` object. A `MoneyCurrencyPairProvider` or something like this.

I think @sagikazarmark planned to work on such library

**Comment by sagikazarmark** [comment]
Yeah, it is planned.

First I though it could be good if this library provided the Money integration out-of-the-box. But after some discussion with @florianv we agreed that Swap is quite generic this way, and it is good it is not tied to anything else. So my plan is to create a wrapper that accepts a Swap object and uses Money/CurrencyPair. This way everything is separated which is SOLID.

**Comment by umpirsky** [comment]
Yes, I like that generic approach. Gives lots of flexibility.

Wrapper sounds right.

**Comment by sagikazarmark** [comment]
Now that Money supports exchanging (and has builtin support for Swap), this one can probably be closed.

**Comment by umpirsky** [comment]
Yep.
