### ISSUE TITLE
Historical Rates

### ISSUE THREAD

**Issue by stelgenhof** [florianv/swap#7]
Hi,

Thank you for this great library! Would it be possible to retrieve historical rates? For example I would like to pull yesterday's or end of last year's exchange rate.

Thanks! Sacha

**Comment by florianv** [comment]
Hello Sacha,

Thanks for your feedback. 

It won't be possible to implement because many providers like Google Finance, Yahoo Finance and Webservicex don't support retrieving historical rates but only the latest ones. Amongst the ones supporting it, there is a difference between the minimum date so it's really specific to each provider.

I suggest you pick a provider supporting them and write your own client.

**Comment by stelgenhof** [comment]
Hello Florian,

Thank you for the feedback. I understand.

Cheers! Sacha
